apiVersion: v2
name: ingress-nginx
version: v4.2.5
appVersion: v1.3.1
description: A Helm chart for ingress-nginx
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: v4.2.5
